component_depth: 2
languages:
  - perl
  - name: perl
    production:
      include:
        - .*/script/mojo_template
        - .*/lib/.*\.pm
        - .*/t/.*\.t
    test:
      include:
        - .*/t/.*\.t