
language: perl
perl:
  - "5.26"
  - "5.24"
  - "5.18"
env: PERL_CPANM_OPT="--notest --force --skip-satisfied"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends libsqlite3-dev
  - cpanm --installdeps .
script:
  - perl Makefile.PL
  - cover -test
after_success:
  - cover -report codecov
  - make manifest
  - make dist