trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: my-secrets-group
- name: PERL_CPANM_OPT
  value: '--notest --force --skip-satisfied'

steps:
- script: sudo apt-get update
  displayName: 'Updating system'

- script: sudo apt-get install -y --no-install-recommends libsqlite3-dev cpanminus sqlite3
  displayName: 'Installing system prerequisites'

- script: |
  sudo echo $(PERL_CPANM_OPT)
  sudo env PERL_CPANM_OPT='--notest --force --skip-satisfied' cpanm --installdeps .
  displayName: 'Installing Perl dependencies'

- script: sudo perl Makefile.PL
  displayName: 'Building project'

- script: sudo env SENTRY_DSN='https://ee5a7463881f4e6493a25c36b506404f:4ebc213840be467fa42e8931fe420149@sentry.io/1472952' cover -test
  displayName: 'Running tests'