trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  PERL_CPANM_OPT: '--notest --force --skip-satisfied'

steps:
- script: echo $PERL_CPANM_OPT
  displayName: 'Show environment variable values'

- script: sudo apt-get update
  displayName: 'Updating system'

- script: sudo apt-get install -y --no-install-recommends libsqlite3-dev cpanminus
  displayName: 'Installing system prerequisites'

- script: sudo cpanm --installdeps .
  displayName: 'Installing Perl dependencies'

- script: sudo perl Makefile.PL
  displayName: 'Building project'

- script: sudo cover -test
  displayName: 'Running tests'