trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: my-secrets-group
- name: PERL_CPANM_OPT
  value: '--notest --force --skip-satisfied'

steps:
- script: echo $PERL_CPANM_OPT
  displayName: 'Show environment variable values'

- script: echo $SENTRY_DSN
  displayName: 'Show environment variable values'

- script: sudo apt-get update
  displayName: 'Updating system'

- script: sudo apt-get install -y --no-install-recommends libsqlite3-dev cpanminus sqlite3
  displayName: 'Installing system prerequisites'

- script: sudo cpanm --installdeps .
  displayName: 'Installing Perl dependencies'

- script: sudo perl Makefile.PL
  displayName: 'Building project'

- script: sudo cover -test
  displayName: 'Running tests'