# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    set_cpanm_opt:
      PERL_CPANM_OPT: '--notest --force --skip-satisfied'

steps:
- script: sudo apt-get update
  displayName: 'Updating system'

- script: sudo apt-get install -y --no-install-recommends libsqlite3-dev cpanminus
  displayName: 'Installing system prerequisites'

- script: sudo cpanm --installdeps .
  displayName: 'Installing Perl dependencies'

- script: perl Makefile.PL
  displayName: 'Building project'

- script: cover -tests
  displayName: 'Running tests'