trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: my-secrets-group

steps:
- script: sudo apt-get update
  displayName: 'Updating system'

- script: sudo apt-get install -y --no-install-recommends libsqlite3-dev cpanminus sqlite3
  displayName: 'Installing system prerequisites'

- script: |
    sudo echo $(PERL_CPANM_OPT)
    sudo env PERL_CPANM_OPT='--notest --force --skip-satisfied' cpanm --installdeps .
  displayName: 'Installing Perl dependencies'

- script: sudo perl Makefile.PL
  displayName: 'Building project'

- script: |
    sudo echo $(SENTRY_DSN)
    sudo env SENTRY_DSN=$(SENTRY_DSN) cover -test
  displayName: 'Running tests'